src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 * fields = {"email"},
 * message = " Email que vous avez indique est deja utlise "
 * )
 */

class User implements UserInterface 
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email();
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="4")
     * @Assert\EqualTo(propertyPath = "confirm_password")
     */
    private $password;

    public $confirm_password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="user")
     */
    private $articles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_profil;
    public $image_profil_update;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_couverture;
    public $image_couverture_update;
    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials() {}
    public function getSalt() {}
    public function getRoles(){
        return ['ROLE_USER'];
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }

    public function getImageProfil()
    {
        return $this->image_profil;
    }

    public function setImageProfil( $image_profil): self
    {
        $this->image_profil = $image_profil;

        return $this;
    }

    public function getImageCouverture()
    {
        return $this->image_couverture;
    }

    public function setImageCouverture($image_couverture): self
    {
        $this->image_couverture = $image_couverture;

        return $this;
    }
}

templates/articleList.html.twig
<div class="col-4"
    style="min-width:300px ;margin-bottom: 10px; border-top: 6px solid dodgerblue; border-left:12px solid white; border-right :12px solid white; ">
    <article>
        <h3>{{ article.title }}</h3>
        <div class="metadata" style="font-size: 13px;"> Ecrit le <span
                style=" color:blue; ">{{article.createdAt | date("d/m/y")}}</span> `a
            <span style="color:blue"> {{ article.createdAt | date(" H:i") }} </span>
            dans le categorie <span style="color: blue;"> {{ article.category.title }} </span> </div>
        <div class="contenu">
            {# <p> {{article.image}} </p> #}
            <img src="/images/articles/{{article.image}}" alt="" style="width:auto;max-width:100% ; max-height: 300px "><br>
            {# <p> {{article.content | raw }} </p> #}
            <p style="font-size:12px ; text-align: justify; " > {{article.description}} </p>
            <span style="border-radius: 50%; font-size:13px; background:rgb(116, 116, 238) ; color:white"> &nbsp;{{article.comments | length}} </span>
            <span style="font-size: 12px;" >Commentaires</span> <br>
            <div class="btn-group">
                <a class="btn btn-primary btn-sm" href="{{path('blog_show',{'id':article.id})}}">Afficher</a>
                {% if app.user %}
                {% if app.user == article.user %}
                <a class="btn btn-success btn-sm " href="{{path('blog_edit',{'id':article.id,'id_u':app.user.id})}}">Modifier</a>
                <a class="btn btn-danger btn-sm " href="{{path('blog_edit',{'id':article.id})}}">Supprimer</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </article>
</div>

templates/base.html.twig
<!DOCTYPE html>
<html>
{# {{ dump(app.user) }} #}
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Welcome!{% endblock %}</title>
  {% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">{% endblock %}
</head>
<nav style = "font-size : 13px"  class="navbar navbar-expand-sm bg-secondary navbar-dark">

  <div class="navbar-header">
    <a class="navbar-brand" href="#">SOcial</a>
  </div>
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{ path('home')}}">Accueil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Liste des Utilisateurs</a>
      </li>

    </ul>
    <ul class="navbar-nav">
      {% if not app.user %}
      <li class="nav-item "><a class="nav-link" href="{{ path('security_login') }}">Connexion</a></li>
      <li class="nav-item "><a class="nav-link" href="{{ path('security_registration') }}">Inscription</a></li>

      {% else %}
       <li class="nav-item" > <img  width  = "50px"   height= "50px" style = "border-radius:50%  " src = "/images/users/profils/{{app.user.imageProfil}}" > </li>
      <li class="nav-link"><a class="btn btn-dark btn-sm"
          href=" {{ path('user_profil',{'id':app.user.id}) }} ">{{app.user.username}}</a> </li>
      <li class="nav-item"> <a class="nav-link" href="{{ path('security_logout') }}">Deconnection</a> </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav" style = "color: black">
      <form action="recherche.php" method="POST" accept-charset="utf-8" class="navbar-nav">
        <li class="nav-item">
          <input type="text" name="serch" placeholder="recherche" class="nav-link form-control" required>
        </li>
        <li class="nav-item">
          <input type="submit" name="" value="rechercher" class="btn btn-dark ">
        </li>
      </form>
    </ul>
  </div>
</nav>

<body class="container">
  <div class="container">
    {% include 'nav_bar_profil.html.twig' %}
    {% block body %} {% endblock %}
    {% block javascripts %}{% endblock %}
</body>
<script src="js/jquery.js"></script>
{% block script %} {% endblock %}

</html>

templates/nav_bar_profil.html.twig
{% if app.user %}

<div class="container">
    <nav class="navbar navbar-expand-sm bg-secondary navbar-dark"
        style="padding-top: 2px; border :2px solid white; font-size:13px ; max-height:40px ">

        <div class="navbar-header">
            <a class="navbar-brand"  href=" {{ path('blog_profil',{'id':app.user.id} ) }} ">My Article <span class="btn btn-success" style="border-radius: 50%;">
                  {% if numberArticle %}    {{ numberArticle}} {% endif %} 
             </span> </a>
        </div>
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('blog_create',{'id':app.user.id})}}">Create Article</a>
                </li>
                 {# <li class="nav-item">
                    <a class="nav-link" href=" {{ path('blog_profil',{'id':app.user.id} ) }} ">My Articles</a>
                </li> #}
                <li class="nav-item"><a class="nav-link"
                    href=" {{ path('user_profil',{'id':app.user.id}) }} ">{{app.user.username}}</a> </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {{ path('security_modif', {'id': app.user.id }) }} ">Modifier mon Profil</a>
                </li>

            </ul>
            <ul class="navbar-nav">
                <li class="nav-item"> <a class="nav-link" href="{{ path('security_logout') }}">Deconnection</a> </li>
            </ul>
        </div>
    </nav>
</div>

{% endif %}

templates/profil_form_comment.html.twig
<div class="form-group">
	{{form_start(commentForm, {'attr':{'action': path('blog_show',{'id':article.id}) }})}}
	{{form_row(commentForm.author, {'attr':{'value':app.user.username}}) }}
	{{form_row(commentForm.authorId, {'attr':{'value':app.user.id}}) }}

	{{form_row(commentForm.content,{'attr':{'class':'from-control','placeholder':'Commentaire'}})}}
	<input class="" type="hidden" name="user" value="{{ app.user.username}}">
	<input type="submit" value="Commenter" class="form-control btn-primary" class="padding-top:-12px">
	{{form_end(commentForm)}}

</div>